spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  mvc:
      static-path-pattern: /static/**
  datasource:
      url: jdbc:mysql://localhost/sell?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: order
  #配置RabbitMQ  之前没有报错是因为用的是默认的配置
  rabbitmq:
    host: loaclhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
env:
  dev
