spring:
  datasource:
    url: jdbc:mysql://localhost/sell?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #配置RabbitMQ  之前没有报错是因为用的是默认的配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认密码为空）
    password:
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
