spring:
  datasource:
    url: jdbc:mysql://localhost/sell?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
